#!/bin/bash
# Apply NVIDIA power management fix (requires sudo)
# This updates the nvidia-graphics-drivers-kms.conf file which is loaded early in boot

set -e

echo "=========================================="
echo "Applying NVIDIA Power Management Fix"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run with sudo"
    echo "Usage: sudo ./apply_nvidia_pm_fix.sh"
    exit 1
fi

echo "Step 1: Removing ineffective configuration files..."
if [ -f /etc/modprobe.d/nvidia-pm.conf ]; then
    rm /etc/modprobe.d/nvidia-pm.conf
    echo "✓ Removed /etc/modprobe.d/nvidia-pm.conf (didn't load early enough)"
else
    echo "  (nvidia-pm.conf not found, skipping)"
fi

if [ -f /usr/lib/modprobe.d/nvidia-runtimepm.conf ]; then
    rm /usr/lib/modprobe.d/nvidia-runtimepm.conf
    echo "✓ Removed /usr/lib/modprobe.d/nvidia-runtimepm.conf (was overriding our settings!)"
else
    echo "  (nvidia-runtimepm.conf not found, skipping)"
fi

if [ -f /etc/udev/rules.d/80-nvidia-pm.rules ]; then
    rm /etc/udev/rules.d/80-nvidia-pm.rules
    echo "✓ Removed /etc/udev/rules.d/80-nvidia-pm.rules (will be replaced with proper config)"
else
    echo "  (80-nvidia-pm.rules not found, skipping)"
fi
echo ""

echo "Step 2: Updating /etc/modprobe.d/nvidia-graphics-drivers-kms.conf..."
tee /etc/modprobe.d/nvidia-graphics-drivers-kms.conf > /dev/null <<'EOF'
# This file was generated by nvidia-driver-550
# Set value to 0 to disable modesetting
options nvidia-drm modeset=1

# NVIDIA GPU Power Management Configuration (CUSTOM - Added for CUDA stability)
# Disable dynamic PM for CUDA stability (no GPU suspend)
options nvidia NVreg_DynamicPowerManagement=0

# Preserve video memory allocations across power state changes
options nvidia NVreg_PreserveVideoMemoryAllocations=1

# Enable PCIe Gen3+ support
options nvidia NVreg_EnablePCIeGen3=1
EOF

echo "✓ Configuration updated"
echo ""

echo "Step 3: Recreating udev rule in proper location..."
tee /etc/udev/rules.d/80-nvidia-pm.rules > /dev/null <<'EOF'
# Disable runtime PM for NVIDIA GPU (device ID 0x2820 = RTX 4070)
# This keeps the GPU awake for CUDA workloads
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{device}=="0x2820", ATTR{power/control}="on"
EOF
echo "✓ udev rule created"
echo ""

echo "Step 4: Reloading udev rules..."
udevadm control --reload-rules
udevadm trigger
echo "✓ udev rules reloaded"
echo ""

echo "Step 5: Rebuilding initramfs for all kernels..."
update-initramfs -u -k all

echo ""
echo "=========================================="
echo "Fix applied successfully!"
echo "=========================================="
echo ""
echo "Cleanup completed:"
echo "  ✓ Removed nvidia-pm.conf (ineffective location)"
echo "  ✓ Removed nvidia-runtimepm.conf (was overriding settings)"
echo "  ✓ Updated nvidia-graphics-drivers-kms.conf (proper early-boot location)"
echo "  ✓ Recreated udev rule"
echo "  ✓ Rebuilt initramfs"
echo ""
echo "REBOOT REQUIRED to apply changes"
echo ""
echo "After reboot, verify with:"
echo "  cat /proc/driver/nvidia/params | grep DynamicPowerManagement"
echo "  (should show: DynamicPowerManagement: 0)"
echo ""
echo "  cat /sys/bus/pci/devices/0000:01:00.0/power/runtime_status"
echo "  (should show: active)"
echo ""
